// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-jKrJEHOpNdTzOso1J8Ox5blwWmjBSmI',
    appId: '1:737837402169:web:a34ba94bef3996d43725e8',
    messagingSenderId: '737837402169',
    projectId: 'messaging-app-a74be',
    authDomain: 'messaging-app-a74be.firebaseapp.com',
    storageBucket: 'messaging-app-a74be.appspot.com',
    measurementId: 'G-WZM9K61LW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpWhK73pLitqA9Ph1kipHtWD0S6VVHuac',
    appId: '1:737837402169:android:98a54ccbc6d94ad23725e8',
    messagingSenderId: '737837402169',
    projectId: 'messaging-app-a74be',
    storageBucket: 'messaging-app-a74be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlpqoTD4fcYbxL6p7kcS4F_4FKpTNJrX0',
    appId: '1:737837402169:ios:dbbc1adfed094b533725e8',
    messagingSenderId: '737837402169',
    projectId: 'messaging-app-a74be',
    storageBucket: 'messaging-app-a74be.appspot.com',
    iosClientId: '737837402169-co34movg2kged4gv6fkl2p399q0t2ri2.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlpqoTD4fcYbxL6p7kcS4F_4FKpTNJrX0',
    appId: '1:737837402169:ios:b6eae9c1c126f2463725e8',
    messagingSenderId: '737837402169',
    projectId: 'messaging-app-a74be',
    storageBucket: 'messaging-app-a74be.appspot.com',
    iosClientId: '737837402169-ltkou40vk0dqmam5nlqt4qdu44vt32pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagingApp.RunnerTests',
  );
}
